var rgrid = false;
rgrid[0, RUMBLE_FORCE_OVERRIDE] = 0;
rgrid[0, RUMBLE_START_TIME] = 0;
rgrid[0, RUMBLE_END_TIME] = 5;
rgrid[0, RUMBLE_LEFT] = 75;
rgrid[0, RUMBLE_RIGHT] = 75;
rgrid[1, RUMBLE_START_TIME] = 10;
rgrid[1, RUMBLE_END_TIME] = 15;
rgrid[1, RUMBLE_LEFT] = 75;
rgrid[1, RUMBLE_RIGHT] = 75;
return rgrid;
