var rgrid = false;
rgrid[0, RUMBLE_FORCE_OVERRIDE] = 0;

rgrid[0, RUMBLE_START_TIME] = 0;
rgrid[0, RUMBLE_END_TIME] = 5;
rgrid[0, RUMBLE_LEFT] = 100;
rgrid[0, RUMBLE_RIGHT] = 100;
rgrid[1, RUMBLE_START_TIME] = 6;
rgrid[1, RUMBLE_END_TIME] = 8;
rgrid[1, RUMBLE_LEFT] = 75;
rgrid[1, RUMBLE_RIGHT] = 75;
rgrid[2, RUMBLE_START_TIME] = 9;
rgrid[2, RUMBLE_END_TIME] = 11;
rgrid[2, RUMBLE_LEFT] = 50;
rgrid[2, RUMBLE_RIGHT] = 50;
rgrid[3, RUMBLE_START_TIME] = 12;
rgrid[3, RUMBLE_END_TIME] = 15;
rgrid[3, RUMBLE_LEFT] = 25;
rgrid[3, RUMBLE_RIGHT] = 25;
return rgrid;
